export const INFO = {
  users: ['Users', 'How many people send a question to the model at the same time. Each user sends exactly one request. More users means more pressure on the GPU.'],
  traffic: ['Traffic type', 'The pattern in which requests arrive. Flood: everyone arrives at the same instant. Steady: requests arrive evenly, one after another. Burst: calm traffic with sudden spikes. Mixed: many short questions together with a few long ones.'],
  prompt: ['Prompt', 'The question every user asks. Short, Explanation and Long change how many words the model must write back, so they change how long each request takes. A custom prompt lets you type your own.'],
  sla: ['SLA target', 'The promised maximum waiting time for one answer. If the answer arrives after this time, the promise is broken. Both schedulers are given the same target so the comparison is fair.'],
  model: ['Model', 'The AI model that writes the answers. Both schedulers use the same model, so any difference comes from scheduling alone.'],
  mode: ['Run mode', 'Sequential: Static runs first, then Dynamic, on the same GPU, one after the other. This is the fair way on a single GPU. Side by side runs both at once and is only available in the simulation.'],
  source: ['Data source', 'Where the numbers come from. Simulation: a made-up GPU model inside this page. PC GPU: the real GPU of the computer running the control service. Cloud GPU: the college GPU. Recorded run: a real run that was saved earlier and is replayed.'],
  speed: ['Playback speed', 'Only for the simulation. How much faster than real time the simulated run plays.'],
  burst: ['Burst button', 'Adds extra requests while a simulated run is going, to see how each scheduler copes with a sudden crowd. It is locked during the second half of a sequential run so both schedulers see the same traffic.'],
  static: ['Static scheduler', 'The old way. It lets a fixed number of requests (8) run at once and makes the rest wait in line. It never says no, so under heavy load the line grows and late answers pile up.'],
  dynamic: ['VelocityLLM Dynamic', 'The new way. It watches the waiting line, the promised time and the GPU memory, and changes how many requests run at once. If an answer cannot arrive in time it says no early, instead of failing late.'],
  smart: ['VelocityLLM Smart', 'Dynamic plus ten extra rules. It counts tokens instead of requests, predicts the memory a reply will still need, keeps memory limit and SLA limit apart, serves the requests closest to their deadline first, lets short prompts pass long ones, and explains every accept or decline. Opt-in: --policy smart.'],
  active: ['Active', 'Requests the GPU is working on right now.'],
  queued: ['Queued', 'Requests waiting for their turn.'],
  limit: ['Limit', 'The most requests allowed to run at once. Static keeps it fixed at 8. Dynamic raises and lowers it while running.'],
  done: ['Done', 'Requests that were answered.'],
  rejected: ['Rejected', 'Requests turned away at the door because they could not be answered in time or the line was full. Static never turns anyone away.'],
  p95: ['p95', 'Out of 100 answered requests, 95 were faster than this time. It shows how slow the slower requests were.'],
  mem: ['GPU memory', 'How much of the GPU memory is in use. The inference engine reserves a large share at start, so this number often stays high even when the GPU is not busy.'],
  tokens: ['Tokens', 'Tokens are small pieces of words. This is how many the model has written so far. More tokens in the same time means more work done.'],
  timeline: ['Request timeline', 'One bar per request, from the moment it arrived until its answer came back. Green: answered within the promised time. Orange: answered too late. Red: rejected or failed. The dark tick on each bar marks the deadline.'],
  concurrency: ['Concurrency chart', 'The grey dashed line is the fixed limit of Static. The orange line is the limit of Dynamic, which moves as the controller reacts. The shaded areas show how many requests were really running. When a queue builds up, Dynamic raises its limit quickly, then stops once replies start taking too long.'],
  log: ['Execution log', 'Every step taken by the schedulers, one line at a time, with the time it happened. Admission: letting a request in or turning it away. Controller: changing the limit. Lifecycle: a request starting or finishing. System: engine start-up and shutdown.'],
  p50: ['p50 (median)', 'Half of the answered requests were faster than this. The typical waiting time.'],
  p99: ['p99', 'Out of 100 answered requests, 99 were faster than this. It is close to the worst waiting time, and it is what unhappy users feel.'],
  goodput: ['On-time tokens per second', 'Only the text from answers that arrived within the SLA, divided by the run time. Late answers do not count, so a scheduler cannot look good by being slow.'],
  tokps: ['Tokens per second', 'How much text the system writes every second in total. Higher means the GPU is used better. It is only compared when both schedulers answered a similar amount of text.'],
  slaServed: ['Within SLA (of served)', 'Of the requests that were answered, the share that arrived within the promised time.'],
  slaOffered: ['Answered on time', 'How many of the users got their reply within the promised time. A declined request counts as not on time, so this is the strictest view.'],
  served: ['Served', 'Requests that received an answer.'],
  errors: ['Failed requests', 'Requests that broke because of an error, for example a lost connection or a timeout.'],
  pressure: ['Pressure test', 'Runs the same traffic at growing sizes, for example 30, 60, 100 and 150 users, for both schedulers. It shows where Static starts to break its promise and how Dynamic holds up as the pressure rises.'],
  levels: ['Load levels', 'The user counts to test, separated by commas. Between 1 and 200 users, up to 8 levels.'],
  sweepP99: ['Chart: p99 latency', 'How slow the slowest answers were as the number of users grew. Lower is better. The dashed line is the SLA.'],
  sweepSla: ['Chart: answered on time', 'Of all users at each load, the share that got an answer within the SLA. Declined requests count as misses. Higher is better.'],
  saved: ['Saved benchmarks', 'Every real run is saved by the control service. You can replay a saved run later without any GPU, which is what you use in front of judges.'],
  replay: ['Replay', 'Plays a saved real run again with the same logs, timeline and numbers, at the original or a faster speed. It is marked as a recorded run so nobody mistakes it for a live one.'],
  repeats: ['Repeats', 'Runs the whole comparison several times, alternating which scheduler goes first, and reports the median. One run can be thrown off by a warm or cold GPU, so 3 or 5 repeats give a fairer answer but take longer.'],
}
